# Generated by Django 5.1.4 on 2026-09-25 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bed_number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("cleaning", "Cleaning"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "ward_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("icu", "ICU"),
                            ("maternity", "Maternity"),
                            ("paediatric", "Paediatric"),
                            ("isolation", "Isolation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("floor", models.PositiveIntegerField()),
                ("total_beds", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admitted_at", models.DateTimeField(auto_now_add=True)),
                ("discharged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attending_doctor_name",
                    models.CharField(default="Dr. On Duty", max_length=150),
                ),
                (
                    "summary_report_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admissions",
                        to="patients.bed",
                    ),
                ),
            ],
            options={
                "ordering": ["-admitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mrn", models.CharField(max_length=30, unique=True)),
                ("full_name", models.CharField(max_length=150)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("blood_group", models.CharField(blank=True, max_length=5, null=True)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "nid",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                (
                    "patient_type",
                    models.CharField(
                        choices=[("opd", "OPD"), ("ipd", "IPD")],
                        default="opd",
                        max_length=10,
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("allergies", models.JSONField(blank=True, default=list)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="patients.admission",
                    ),
                ),
            ],
            options={
                "ordering": ["-registered_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalHistoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by_name",
                    models.CharField(default="System", max_length=150),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("diagnosis", "Diagnosis"),
                            ("procedure", "Procedure"),
                            ("allergy", "Allergy"),
                            ("medication", "Medication"),
                            ("note", "Note"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("details", models.TextField(blank=True, default="")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.AddField(
            model_name="bed",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admissions",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="bed",
            name="ward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beds",
                to="patients.ward",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="ward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admissions",
                to="patients.ward",
            ),
        ),
    ]
