# Generated by Django 5.1.4 on 2026-09-25 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="patient_id",
        ),
        migrations.AddField(
            model_name="user",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_account",
                to="patients.patient",
            ),
        ),
    ]
