# Generated by Django 5.1.4 on 2026-09-25 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_patient_id_user_patient"),
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_account",
                to="appointments.doctor",
            ),
        ),
    ]
