# Generated by Django 5.1.4 on 2026-09-25 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.PositiveIntegerField(db_index=True)),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="lab.reportdocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-downloaded_at"],
            },
        ),
    ]
