# Generated by Django 5.1.4 on 2026-09-25 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("name_bn", models.CharField(blank=True, default="", max_length=150)),
                ("specialty", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("room_number", models.CharField(max_length=20)),
                ("designation", models.JSONField(blank=True, default=dict)),
                (
                    "qualifications",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("experience_years", models.PositiveIntegerField(default=0)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=10,
                    ),
                ),
                ("bio", models.JSONField(blank=True, default=dict)),
                ("photo_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("patient_name", models.CharField(max_length=150)),
                ("patient_mrn", models.CharField(max_length=30)),
                ("doctor_name", models.CharField(max_length=150)),
                ("specialty", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("booked", "Booked"),
                            ("checked_in", "Checked in"),
                            ("in_consultation", "In consultation"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No show"),
                        ],
                        default="booked",
                        max_length=20,
                    ),
                ),
                ("token_number", models.PositiveIntegerField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="appointments.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "date"], name="appointment_doctor__e7d63f_idx"
                    ),
                    models.Index(
                        fields=["patient_id"], name="appointment_patient_94a7ef_idx"
                    ),
                    models.Index(
                        fields=["status"], name="appointment_status_8fe9d7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("slot_minutes", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="appointments.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "weekday"],
                        name="appointment_doctor__eb2a25_idx",
                    )
                ],
            },
        ),
    ]
