# Generated by Django 5.1.4 on 2026-09-25 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("icon", models.CharField(max_length=50)),
                ("image", models.CharField(max_length=255)),
                ("name", models.JSONField()),
                ("summary", models.JSONField()),
                ("description", models.JSONField()),
                ("services", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="HealthPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.JSONField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_popular", models.BooleanField(default=False)),
                ("tests", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="HospitalService",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("icon", models.CharField(max_length=50)),
                ("image", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("clinical", "Clinical"),
                            ("diagnostic", "Diagnostic"),
                            ("support", "Support"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_emergency", models.BooleanField(default=False)),
                ("name", models.JSONField()),
                ("summary", models.JSONField()),
                ("description", models.JSONField()),
                ("features", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.JSONField()),
                ("location", models.JSONField()),
                ("quote", models.JSONField()),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="GuestBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=30, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("age", models.PositiveIntegerField()),
                ("gender", models.CharField(max_length=10)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_booking",
                        to="appointments.appointment",
                    ),
                ),
            ],
        ),
    ]
