# Generated by Django 5.1.4 on 2026-09-25 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("specimen", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=30)),
                (
                    "reference_low",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "reference_high",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("turnaround_hours", models.PositiveIntegerField(default=24)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ReportDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.PositiveIntegerField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("lab_report", "Lab report"),
                            ("prescription", "Prescription"),
                            ("discharge_summary", "Discharge summary"),
                            ("invoice", "Invoice"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("downloaded", "Downloaded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("downloaded_at", models.DateTimeField(blank=True, null=True)),
                ("size_bytes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "related_order_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=30, unique=True)),
                ("patient_id", models.PositiveIntegerField(db_index=True)),
                ("patient_name", models.CharField(max_length=150)),
                ("patient_mrn", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "Ordered"),
                            ("sample_collected", "Sample collected"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="ordered",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("urgent", "Urgent"), ("routine", "Routine")],
                        default="routine",
                        max_length=10,
                    ),
                ),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                ("sample_collected_at", models.DateTimeField(blank=True, null=True)),
                ("sample_id", models.CharField(blank=True, max_length=30, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("clinical_notes", models.TextField(blank=True, default="")),
                (
                    "ordered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tests",
                    models.ManyToManyField(related_name="orders", to="lab.labtest"),
                ),
                (
                    "report",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_order",
                        to="lab.reportdocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "reference_low",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "reference_high",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="lab.laborder",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lab.labtest",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
