"""
Ports the demo users/passwords and representative content from
src/app/core/mock/db.ts and src/app/core/mock/seeds/*.ts so a fresh
`manage.py migrate && manage.py seed_demo` gives the same login screen and a
working demo dataset. Idempotent: safe to re-run.

Scope note: the mock's appointment/lab/billing history is generated by a
seeded PRNG across a rolling 15-day window, which is inherently
time-relative and not meaningful to port verbatim into fixed rows. This
command instead seeds a small, representative set of appointments, lab
orders and invoices (a handful of realistic rows) rather than reproducing
that generator — enough to exercise every endpoint and role in the demo.
"""

from datetime import date, time, timedelta
from decimal import Decimal

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from django.utils import timezone

from appointments.models import Appointment, AppointmentStatus, Doctor, DoctorSchedule
from billing.models import Invoice, InvoiceLineItem
from inventory.models import InventoryItem, Supplier
from lab.models import LabOrder, LabOrderStatus, LabTest
from patients.models import Bed, MedicalHistoryEntry, Patient, Ward
from public_site.models import Department, HealthPackage, HospitalService, Testimonial

User = get_user_model()
DEMO_PASSWORD = "demo1234"


def l(en: str, bn: str) -> dict:
    return {"en": en, "bn": bn}


DEMO_USERS = [
    # (id, username, role, first_name, last_name, patient_index, doctor_index)
    (1, "admin", "admin", "Ayesha", "Rahman", None, None),
    (2, "doctor", "doctor", "Imran", "Hossain", None, 1),  # linked to Dr. Imran Hossain, seeded below
    (3, "nurse", "nurse", "Nusrat", "Jahan", None, None),
    (4, "reception", "receptionist", "Tanvir", "Ahmed", None, None),
    (5, "lab", "lab_technician", "Sabbir", "Khan", None, None),
    (6, "pharmacy", "pharmacist", "Farhana", "Akter", None, None),
    (7, "patient", "patient", "Rafiqul", "Islam", 1, None),  # linked to patient #1, seeded below
]

DOCTOR_SEED = [
    ("Dr. Imran Hossain", "ডা. ইমরান হোসেন", "Cardiology", "Medicine", "1200.00", "C-201", 22, "male"),
    ("Dr. Shahana Parvin", "ডা. শাহানা পারভীন", "Obstetrics", "Maternity", "1000.00", "M-104", 20, "female"),
    ("Dr. Mahbub Alam", "ডা. মাহবুব আলম", "Orthopaedics", "Surgery", "1500.00", "S-310", 16, "male"),
    ("Dr. Tahmina Rashid", "ডা. তাহমিনা রশিদ", "Paediatrics", "Paediatrics", "900.00", "P-112", 14, "female"),
    ("Dr. Kazi Nurul", "ডা. কাজী নুরুল", "General Medicine", "Medicine", "800.00", "C-105", 11, "male"),
    ("Dr. Sadia Islam", "ডা. সাদিয়া ইসলাম", "Dermatology", "Medicine", "1100.00", "C-208", 9, "female"),
    ("Dr. Rezaul Karim", "ডা. রেজাউল করিম", "Neurology", "Medicine", "1800.00", "C-312", 24, "male"),
    ("Dr. Farzana Haque", "ডা. ফারজানা হক", "ENT", "Surgery", "1000.00", "S-205", 13, "female"),
    ("Dr. Nasrin Sultana", "ডা. নাসরিন সুলতানা", "Obstetrics", "Maternity", "1200.00", "M-108", 10, "female"),
    ("Dr. Ashraful Haque", "ডা. আশরাফুল হক", "Cardiology", "Medicine", "1500.00", "C-204", 15, "male"),
    ("Dr. Mizanur Rahman", "ডা. মিজানুর রহমান", "Paediatrics", "Paediatrics", "1000.00", "P-115", 8, "male"),
    ("Dr. Rumana Afroz", "ডা. রুমানা আফরোজ", "General Medicine", "Medicine", "700.00", "C-110", 7, "female"),
    ("Dr. Shafiqul Islam", "ডা. শফিকুল ইসলাম", "Orthopaedics", "Surgery", "1200.00", "S-312", 9, "male"),
    ("Dr. Laila Arjumand", "ডা. লায়লা আরজুমান্দ", "Dermatology", "Medicine", "1000.00", "C-210", 12, "female"),
    ("Dr. Jahangir Kabir", "ডা. জাহাঙ্গীর কবির", "Neurology", "Medicine", "1600.00", "C-315", 17, "male"),
    ("Dr. Mehnaz Chowdhury", "ডা. মেহনাজ চৌধুরী", "ENT", "Surgery", "900.00", "S-207", 6, "female"),
]

DEPARTMENT_SEED = [
    {
        "slug": "cardiology", "icon": "heart-pulse", "image": "/images/departments/cardiology.webp",
        "name": l("Cardiology", "কার্ডিওলজি"),
        "summary": l("Heart care from ECG and echo to cath-lab interventions.", "ইসিজি ও ইকো থেকে ক্যাথ-ল্যাব পর্যন্ত সম্পূর্ণ হৃদরোগ চিকিৎসা।"),
        "description": l("Our cardiology team diagnoses and treats heart and blood-vessel disease.", "আমাদের কার্ডিওলজি টিম হৃদ্‌যন্ত্র ও রক্তনালির রোগ নির্ণয় ও চিকিৎসা করে।"),
        "services": [l("ECG, Echo & ETT", "ইসিজি, ইকো ও ইটিটি"), l("24/7 CCU", "২৪/৭ সিসিইউ")],
    },
    {
        "slug": "gynae-obstetrics", "icon": "mother", "image": "/images/departments/gynae-obstetrics.webp",
        "name": l("Gynae & Obstetrics", "গাইনি ও প্রসূতি"),
        "summary": l("Antenatal care, safe delivery and women's health.", "গর্ভকালীন সেবা, নিরাপদ প্রসব ও নারী স্বাস্থ্য।"),
        "description": l("From the first antenatal visit to postnatal follow-up.", "প্রথম গর্ভকালীন চেকআপ থেকে প্রসব-পরবর্তী ফলোআপ পর্যন্ত।"),
        "services": [l("Antenatal & postnatal care", "গর্ভকালীন ও প্রসব-পরবর্তী সেবা")],
    },
    {
        "slug": "orthopaedics", "icon": "bone", "image": "/images/departments/orthopaedics.webp",
        "name": l("Orthopaedics", "অর্থোপেডিক্স"),
        "summary": l("Bones, joints, spine and sports injuries.", "হাড়, জয়েন্ট, মেরুদণ্ড ও খেলাধুলাজনিত আঘাত।"),
        "description": l("Treats fractures, arthritis, spine problems and sports injuries.", "হাড় ভাঙা, আর্থ্রাইটিস, মেরুদণ্ডের সমস্যার চিকিৎসা।"),
        "services": [l("Fracture management", "হাড় ভাঙার চিকিৎসা")],
    },
    {
        "slug": "paediatrics", "icon": "baby", "image": "/images/departments/paediatrics.webp",
        "name": l("Paediatrics", "শিশু বিভাগ"),
        "summary": l("Care for newborns, children and adolescents.", "নবজাতক, শিশু ও কিশোরদের চিকিৎসা।"),
        "description": l("Vaccinations, growth monitoring, childhood illness and NICU.", "টিকা, বৃদ্ধি পর্যবেক্ষণ, শিশুরোগ ও এনআইসিইউ।"),
        "services": [l("Vaccination", "টিকাদান")],
    },
    {
        "slug": "medicine", "icon": "stethoscope", "image": "/images/departments/medicine.webp",
        "name": l("Internal Medicine", "মেডিসিন"),
        "summary": l("Diabetes, blood pressure, fever and chronic disease.", "ডায়াবেটিস, উচ্চ রক্তচাপ, জ্বর ও দীর্ঘমেয়াদি রোগ।"),
        "description": l("Diagnoses and manages diabetes, hypertension, infections.", "ডায়াবেটিস, উচ্চ রক্তচাপ, সংক্রমণ নির্ণয় ও নিয়ন্ত্রণ।"),
        "services": [l("Diabetes clinic", "ডায়াবেটিস ক্লিনিক")],
    },
    {
        "slug": "dermatology", "icon": "sparkles", "image": "/images/departments/dermatology.webp",
        "name": l("Dermatology", "চর্মরোগ"),
        "summary": l("Skin, hair and nail conditions.", "ত্বক, চুল ও নখের রোগ।"),
        "description": l("Treats acne, eczema, psoriasis, fungal infections and hair loss.", "ব্রণ, একজিমা, সোরিয়াসিস, ছত্রাক সংক্রমণ ও চুল পড়ার চিকিৎসা।"),
        "services": [l("Acne & eczema", "ব্রণ ও একজিমা")],
    },
    {
        "slug": "neurology", "icon": "brain", "image": "/images/departments/neurology.webp",
        "name": l("Neurology", "নিউরোলজি"),
        "summary": l("Stroke, epilepsy, headache and nerve disorders.", "স্ট্রোক, মৃগী, মাথাব্যথা ও স্নায়ুরোগ।"),
        "description": l("Treats disorders of the brain, spine and nerves.", "মস্তিষ্ক, মেরুদণ্ড ও স্নায়ুর রোগের চিকিৎসা।"),
        "services": [l("Stroke care", "স্ট্রোক চিকিৎসা")],
    },
    {
        "slug": "ent", "icon": "ear", "image": "/images/departments/ent.webp",
        "name": l("ENT", "নাক, কান ও গলা"),
        "summary": l("Ear, nose, throat, head and neck.", "নাক, কান, গলা, মাথা ও ঘাড়।"),
        "description": l("Treats hearing loss, sinusitis, tonsillitis and voice problems.", "শ্রবণশক্তি হ্রাস, সাইনোসাইটিস, টনসিলাইটিসের চিকিৎসা।"),
        "services": [l("Audiometry", "অডিওমেট্রি")],
    },
]

SERVICE_SEED = [
    {"slug": "emergency", "icon": "siren", "image": "/images/services/emergency.webp", "category": "clinical", "is_emergency": True,
     "name": l("24/7 Emergency", "২৪/৭ জরুরি বিভাগ"), "summary": l("Round-the-clock emergency and trauma care.", "সার্বক্ষণিক জরুরি ও ট্রমা চিকিৎসা।"),
     "description": l("Open every hour, staffed by emergency physicians.", "জরুরি চিকিৎসক দিয়ে সার্বক্ষণিক প্রস্তুত।"), "features": [l("Triage within 10 minutes", "১০ মিনিটের মধ্যে ট্রায়াজ")]},
    {"slug": "icu", "icon": "bed", "image": "/images/services/icu.webp", "category": "clinical", "is_emergency": False,
     "name": l("ICU, CCU & NICU", "আইসিইউ, সিসিইউ ও এনআইসিইউ"), "summary": l("Intensive care for adults, cardiac patients and newborns.", "প্রাপ্তবয়স্ক, হৃদরোগী ও নবজাতকের নিবিড় পরিচর্যা।"),
     "description": l("Forty intensive-care beds with ventilator support.", "৪০টি নিবিড় পরিচর্যা শয্যা।"), "features": [l("Ventilator support", "ভেন্টিলেটর সাপোর্ট")]},
    {"slug": "diagnostics", "icon": "microscope", "image": "/images/services/diagnostics.webp", "category": "diagnostic", "is_emergency": False,
     "name": l("Laboratory & Diagnostics", "ল্যাবরেটরি ও ডায়াগনস্টিক"), "summary": l("Pathology, imaging and reports you can download online.", "প্যাথলজি, ইমেজিং এবং অনলাইনে রিপোর্ট ডাউনলোড।"),
     "description": l("A fully automated laboratory and imaging suite.", "সম্পূর্ণ স্বয়ংক্রিয় ল্যাবরেটরি ও ইমেজিং সুবিধা।"), "features": [l("CT & 1.5T MRI", "সিটি ও ১.৫টি এমআরআই")]},
    {"slug": "surgery", "icon": "syringe", "image": "/images/services/surgery.webp", "category": "clinical", "is_emergency": False,
     "name": l("Operation Theatres", "অপারেশন থিয়েটার"), "summary": l("Modular theatres for general and specialist surgery.", "সাধারণ ও বিশেষায়িত সার্জারির জন্য মডুলার থিয়েটার।"),
     "description": l("Six modular operation theatres with laminar airflow.", "ল্যামিনার এয়ারফ্লোসহ ছয়টি মডুলার অপারেশন থিয়েটার।"), "features": [l("Laminar airflow", "ল্যামিনার এয়ারফ্লো")]},
    {"slug": "dialysis", "icon": "droplet", "image": "/images/services/dialysis.webp", "category": "clinical", "is_emergency": False,
     "name": l("Dialysis", "ডায়ালাইসিস"), "summary": l("Haemodialysis in a calm, dedicated unit.", "নিরিবিলি পৃথক ইউনিটে হিমোডায়ালাইসিস।"),
     "description": l("Twelve haemodialysis stations with nephrologist supervision.", "নেফ্রোলজিস্টের তত্ত্বাবধানে ১২টি স্টেশন।"), "features": [l("12 stations", "১২টি স্টেশন")]},
    {"slug": "pharmacy", "icon": "pill", "image": "/images/services/pharmacy.webp", "category": "support", "is_emergency": False,
     "name": l("24-Hour Pharmacy", "২৪ ঘণ্টা ফার্মেসি"), "summary": l("Genuine medicines, open day and night.", "আসল ওষুধ, দিনরাত খোলা।"),
     "description": l("In-house pharmacy stocked directly from licensed manufacturers.", "লাইসেন্সপ্রাপ্ত প্রস্তুতকারকের ওষুধ।"), "features": [l("Open 24 hours", "২৪ ঘণ্টা খোলা")]},
    {"slug": "ambulance", "icon": "ambulance", "image": "/images/services/ambulance.webp", "category": "support", "is_emergency": True,
     "name": l("Ambulance Service", "অ্যাম্বুলেন্স সেবা"), "summary": l("ICU and standard ambulances across the city.", "শহরজুড়ে আইসিইউ ও সাধারণ অ্যাম্বুলেন্স।"),
     "description": l("Call the hotline for an ICU or standard ambulance.", "হটলাইনে কল করুন।"), "features": [l("ICU ambulance", "আইসিইউ অ্যাম্বুলেন্স")]},
    {"slug": "health-checkup", "icon": "clipboard-check", "image": "/images/services/health-checkup.webp", "category": "diagnostic", "is_emergency": False,
     "name": l("Health Check-up", "স্বাস্থ্য পরীক্ষা"), "summary": l("Preventive packages for every age.", "সব বয়সের জন্য প্রতিরোধমূলক প্যাকেজ।"),
     "description": l("Screening packages bundling tests with physician review.", "প্রয়োজনীয় পরীক্ষা ও চিকিৎসকের পর্যালোচনা।"), "features": [l("Same-day results", "একই দিনে ফলাফল")]},
]

PACKAGE_SEED = [
    {"name": l("Basic Health Check", "বেসিক হেলথ চেক"), "price": "2500.00", "is_popular": False,
     "tests": [l("Complete blood count", "কমপ্লিট ব্লাড কাউন্ট"), l("Physician consultation", "চিকিৎসকের পরামর্শ")]},
    {"name": l("Executive Health Check", "এক্সিকিউটিভ হেলথ চেক"), "price": "6500.00", "is_popular": True,
     "tests": [l("Everything in Basic", "বেসিকের সবকিছু"), l("ECG & echocardiogram", "ইসিজি ও ইকোকার্ডিওগ্রাম")]},
    {"name": l("Senior Citizen Check", "প্রবীণ স্বাস্থ্য পরীক্ষা"), "price": "8500.00", "is_popular": False,
     "tests": [l("Everything in Executive", "এক্সিকিউটিভের সবকিছু"), l("Bone density (DEXA)", "হাড়ের ঘনত্ব (ডেক্সা)")]},
]

TESTIMONIAL_SEED = [
    {"name": l("Nazmul Hasan", "নাজমুল হাসান"), "location": l("Mirpur, Dhaka", "মিরপুর, ঢাকা"),
     "quote": l("My father was taken to the CCU at 2 AM and the team had him stable within the hour.", "রাত ২টায় বাবাকে সিসিইউতে নেওয়া হয় এবং এক ঘণ্টার মধ্যে টিম তাঁকে স্থিতিশীল করে।")},
    {"name": l("Sharmin Akter", "শারমিন আক্তার"), "location": l("Uttara, Dhaka", "উত্তরা, ঢাকা"),
     "quote": l("Booking online took two minutes and I was seen at my slot time.", "অনলাইনে বুকিং করতে দুই মিনিট লেগেছে এবং নির্ধারিত সময়েই ডাক্তার দেখিয়েছি।")},
    {"name": l("Abdul Mannan", "আব্দুল মান্নান"), "location": l("Narayanganj", "নারায়ণগঞ্জ"),
     "quote": l("After my knee replacement the physiotherapy team had me walking in two days.", "হাঁটু প্রতিস্থাপনের পর ফিজিওথেরাপি টিম দুই দিনের মধ্যেই আমাকে হাঁটিয়েছে।")},
]

PATIENT_SEED = [
    ("Rafiqul Islam", "male", "1978-04-12", "01712345678", "House 12, Road 5, Dhanmondi, Dhaka"),
    ("Moushumi Akter", "female", "1990-08-22", "01812345679", "Flat 4B, Baridhara, Dhaka"),
    ("Kamal Uddin", "male", "1965-01-30", "01912345680", "Chandgaon, Chattogram"),
    ("Shirin Sultana", "female", "2001-11-05", "01612345681", "Sylhet Sadar, Sylhet"),
    ("Habibur Rahman", "male", "1955-06-18", "01512345682", "Boalia, Rajshahi"),
]


class Command(BaseCommand):
    help = "Seeds demo users and representative content ported from the Angular mock's db.ts/seeds."

    def handle(self, *args, **options):
        patients = self._seed_patients()
        doctors = self._seed_doctors_and_schedules()
        self._seed_users(patients, doctors)
        self._seed_wards_and_beds(patients)
        self._seed_appointments(doctors, patients)
        self._seed_public_content()
        self._seed_inventory()
        self._seed_lab(patients)
        self._seed_billing(patients)
        self.stdout.write(self.style.SUCCESS("Demo data seeded."))

    def _seed_users(self, patients, doctors):
        for _id, username, role, first_name, last_name, patient_index, doctor_index in DEMO_USERS:
            patient = patients[patient_index - 1] if patient_index else None
            doctor = doctors[doctor_index - 1] if doctor_index else None

            user, created = User.objects.get_or_create(
                username=username,
                defaults={
                    "role": role,
                    "first_name": first_name,
                    "last_name": last_name,
                    "email": f"{username}@hms.example",
                    "staff_id": None if role == "patient" else f"EMP-{_id:04d}",
                    "patient": patient,
                    "doctor": doctor,
                },
            )
            if created:
                user.set_password(DEMO_PASSWORD)
                user.save()
            elif user.patient_id != (patient.id if patient else None) or user.doctor_id != (
                doctor.id if doctor else None
            ):
                # Self-healing: re-running against a DB seeded before this link
                # existed (e.g. before `doctor` was added) should still end up
                # linked, not just on first creation.
                user.patient = patient
                user.doctor = doctor
                user.save(update_fields=["patient", "doctor"])
        self.stdout.write(f"Users: {User.objects.count()}")

    def _seed_patients(self):
        patients = []
        for i, (full_name, gender, dob, phone, address) in enumerate(PATIENT_SEED, start=1):
            patient, _ = Patient.objects.get_or_create(
                mrn=f"HMS-2026-{i:04d}",
                defaults={
                    "full_name": full_name,
                    "gender": gender,
                    "date_of_birth": dob,
                    "phone": phone,
                    "address": address,
                    "patient_type": "opd",
                    "allergies": [],
                },
            )
            patients.append(patient)
        self.stdout.write(f"Patients: {len(patients)}")
        return patients

    def _seed_wards_and_beds(self, patients):
        ward_specs = [
            ("General Ward A", "general", 1, 10),
            ("ICU", "icu", 2, 6),
            ("Maternity Ward", "maternity", 3, 8),
        ]
        for name, ward_type, floor, total_beds in ward_specs:
            ward, _ = Ward.objects.get_or_create(
                name=name, defaults={"ward_type": ward_type, "floor": floor, "total_beds": total_beds}
            )
            for n in range(1, total_beds + 1):
                Bed.objects.get_or_create(ward=ward, bed_number=f"{ward.id}-{n:02d}")
        self.stdout.write(f"Wards: {Ward.objects.count()}, Beds: {Bed.objects.count()}")

    def _seed_doctors_and_schedules(self):
        doctors = []
        for full_name, name_bn, specialty, department, fee, room, experience, gender in DOCTOR_SEED:
            doctor, created = Doctor.objects.get_or_create(
                full_name=full_name,
                defaults={
                    "name_bn": name_bn,
                    "specialty": specialty,
                    "department": department,
                    "consultation_fee": fee,
                    "room_number": room,
                    "experience_years": experience,
                    "gender": gender,
                    "qualifications": "MBBS, FCPS",
                    "designation": l("Consultant", "কনসালট্যান্ট"),
                    "bio": l(f"{full_name} is a specialist in {specialty}.", ""),
                },
            )
            doctors.append(doctor)
            if created:
                for weekday in (0, 1, 2, 3, 4):
                    if weekday == doctor.id % 5:
                        continue
                    morning = doctor.id % 2 == 1
                    DoctorSchedule.objects.create(
                        doctor=doctor,
                        weekday=weekday,
                        start_time=time(9, 0) if morning else time(15, 0),
                        end_time=time(13, 0) if morning else time(19, 0),
                        slot_minutes=20,
                        is_active=True,
                    )
        self.stdout.write(f"Doctors: {len(doctors)}, Schedules: {DoctorSchedule.objects.count()}")
        return doctors

    def _seed_appointments(self, doctors, patients):
        if Appointment.objects.exists():
            return
        today = date.today()
        statuses = [
            AppointmentStatus.COMPLETED,
            AppointmentStatus.COMPLETED,
            AppointmentStatus.CHECKED_IN,
            AppointmentStatus.BOOKED,
            AppointmentStatus.BOOKED,
        ]
        for i, (doctor, patient, status) in enumerate(zip(doctors, patients * 4, statuses)):
            offset = i - 2
            Appointment.objects.create(
                patient_id=patient.id,
                patient_name=patient.full_name,
                patient_mrn=patient.mrn,
                doctor=doctor,
                doctor_name=doctor.full_name,
                specialty=doctor.specialty,
                date=today + timedelta(days=offset),
                start_time=time(9, 0 + i),
                end_time=time(9, 20 + i),
                status=status,
                token_number=i + 1,
                reason="Follow-up consultation",
                checked_in_at=timezone.now() if status != AppointmentStatus.BOOKED else None,
            )
        self.stdout.write(f"Appointments: {Appointment.objects.count()}")

    def _seed_public_content(self):
        for dept in DEPARTMENT_SEED:
            Department.objects.get_or_create(slug=dept["slug"], defaults=dept)
        for service in SERVICE_SEED:
            HospitalService.objects.get_or_create(slug=service["slug"], defaults=service)
        for package in PACKAGE_SEED:
            HealthPackage.objects.get_or_create(name=package["name"], defaults=package)
        for testimonial in TESTIMONIAL_SEED:
            Testimonial.objects.get_or_create(name=testimonial["name"], defaults=testimonial)
        self.stdout.write(
            f"Departments: {Department.objects.count()}, Services: {HospitalService.objects.count()}, "
            f"Packages: {HealthPackage.objects.count()}, Testimonials: {Testimonial.objects.count()}"
        )

    def _seed_inventory(self):
        supplier, _ = Supplier.objects.get_or_create(
            name="ACME Pharma Ltd.", defaults={"contact_person": "Karim Uddin", "phone": "01700000000", "is_active": True}
        )
        items = [
            ("PARA500", "Paracetamol 500mg", "medicine", "tablet", 20, "2.50"),
            ("AMOX250", "Amoxicillin 250mg", "medicine", "capsule", 15, "5.50"),
            ("SYR001", "Disposable Syringe 5ml", "consumable", "pcs", 100, "3.00"),
            ("BP001", "BP Monitor", "equipment", "unit", 2, "2500.00"),
        ]
        for code, name, category, unit, reorder, price in items:
            InventoryItem.objects.get_or_create(
                code=code,
                defaults={
                    "name": name, "category": category, "unit": unit, "quantity_in_stock": reorder * 3,
                    "reorder_level": reorder, "unit_price": price, "supplier": supplier, "is_active": True,
                },
            )
        self.stdout.write(f"Inventory items: {InventoryItem.objects.count()}")

    def _seed_lab(self, patients):
        tests = [
            ("CBC", "Complete Blood Count", "Blood", "cells/uL", "4.5", "11.0", "500.00", 24),
            ("FBS", "Fasting Blood Sugar", "Blood", "mg/dL", "70", "100", "300.00", 12),
            ("LFT", "Liver Function Test", "Blood", "U/L", "5", "40", "800.00", 24),
        ]
        for code, name, specimen, unit, low, high, price, hours in tests:
            LabTest.objects.get_or_create(
                code=code,
                defaults={
                    "name": name, "specimen": specimen, "unit": unit, "reference_low": low,
                    "reference_high": high, "price": price, "turnaround_hours": hours,
                },
            )
        if not LabOrder.objects.exists():
            admin_user = User.objects.filter(username="doctor").first()
            cbc = LabTest.objects.get(code="CBC")
            order = LabOrder.objects.create(
                order_number="LAB-00001",
                patient_id=patients[0].id,
                patient_name=patients[0].full_name,
                patient_mrn=patients[0].mrn,
                ordered_by=admin_user,
                status=LabOrderStatus.ORDERED,
                priority="routine",
            )
            order.tests.set([cbc])
        self.stdout.write(f"Lab tests: {LabTest.objects.count()}, Lab orders: {LabOrder.objects.count()}")

    def _seed_billing(self, patients):
        if Invoice.objects.exists():
            return
        invoice = Invoice.objects.create(
            invoice_number=f"INV-{timezone.now().year}-00001",
            patient_id=patients[0].id,
            patient_name=patients[0].full_name,
            patient_mrn=patients[0].mrn,
            status="unpaid",
            due_date=date.today() + timedelta(days=14),
        )
        InvoiceLineItem.objects.create(
            invoice=invoice, source="consultation", description="Consultation fee",
            quantity=1, unit_price="1200.00",
        )
        self.stdout.write(f"Invoices: {Invoice.objects.count()}")
